### ISSUE TITLE
Please switch to `wb_add_data()`

### ISSUE THREAD

**Issue by JanMarvin** [city-of-baltimore/baltimoreCIP-Workday-EIB#1]
https://github.com/city-of-baltimore/baltimoreCIP-Workday-EIB/blob/0c24e4ed8cac87321e8cd65fd8f8322ee4722044/R/eib-xlsx.R#L58

Hi @elipousson , we want to deprecate `write_data()` and will throw a warning with the upcoming release (https://github.com/JanMarvin/openxlsx2/issues/1060)

You should be able to replace this with `wb$add_data()` and might want to have a look at `wb_dims()`. For questions feel free to reach out.

**Comment by elipousson** [comment]
Thanks for the heads up! Appreciate you creating such a useful package.
